BaiTapLon/Controllers/BaiTapLonController.cs
using BaiTapLon.Models.DAOO;
using BaiTapLon.Models.Entities;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace BaiTapLon.Controllers
{
    public class BaiTapLonController : Controller
    {
        // GET: BaiTapLon
        static List<TungSanPham> listTungSanPham = new List<TungSanPham>();
        public ActionResult Index()
        {
            ViewBag.SanPham = new SanPhamDAO().getAll();
            return View("~/Views/BaiTapLon/index.cshtml");
        }
        public ActionResult Women(string ShoeFirm,String Type)
        {
            ViewBag.SanPham = new BaiTapLon.Models.DAOO.SanPhamDAO().getSanPham(ShoeFirm,Type);
            return View("~/Views/BaiTapLon/women.cshtml");
        }
        public ActionResult WomenShoeFirm(string ShoeFirm)
        {
            ViewBag.SanPham = new BaiTapLon.Models.DAOO.SanPhamDAO().getSanPham(ShoeFirm);
            return View("~/Views/BaiTapLon/women.cshtml");
        }
        public ActionResult Checkout()
        {
            ViewBag.listTungSanPham = listTungSanPham;
            return View("~/Views/BaiTapLon/checkout.cshtml");
        }
        public ActionResult Contact()
        {
            return View("~/Views/BaiTapLon/contact.cshtml");
        }
        public ActionResult Details(string Name)
        {
            ViewBag.SanPham = new BaiTapLon.Models.DAOO.SanPhamDAO().thongTinSanPham(Name);
            return View("~/Views/BaiTapLon/details.cshtml");
        }
        [System.Web.Mvc.HttpGet]
        public ActionResult Login()
        {
            return View("~/Views/BaiTapLon/login.cshtml");
        }

        [System.Web.Mvc.HttpPost]
        public JsonResult Login(string email,string password)
        {
            if (new BaiTapLon.Models.DAOO.LoginDAO().checkUser(email, password) == "Success")
            {
                return Json("Success", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("Erorr", JsonRequestBehavior.AllowGet);
        }

        [System.Web.Mvc.HttpPost]
        public JsonResult creatUser(string FirstName,string LastName,String Email,bool Sex,String Password)
        {
            Login user = new Login();
            user.FirstName = FirstName;
            user.LastName = LastName;
            user.Email = Email;
            user.Sex = true;
            user.Password = Password;
            if (new BaiTapLon.Models.DAOO.LoginDAO().createUser(user) == "Success")
                return Json("Success", JsonRequestBehavior.AllowGet);
            else
                return Json("Erorr", JsonRequestBehavior.AllowGet);
        }

        public ActionResult AddSanPham(String Image, int Price, String Name, String ShoeFirm)
        {
            TungSanPham tungSanPham = new TungSanPham();
            tungSanPham.Image = Image;
            tungSanPham.Price = Price;
            tungSanPham.ShoeFirm = ShoeFirm;
            tungSanPham.Name = Name;
            if (tungSanPham != null)
            {
                listTungSanPham.Add(tungSanPham);
                return Content("Success");
            }
            else
                return Content("Erorr");
        }

        public ActionResult DeleteSanPham(int id)
        {
            listTungSanPham.RemoveAt(id);
            return Content("Success");
        }

        public ActionResult Register()
        {
            return View("~/Views/BaiTapLon/register.cshtml");
        }
    }
}

BaiTapLon/Views/BaiTapLon/checkout.cshtml
<!DOCTYPE HTML>
<html>
<head>
<title>Gretong a Ecommerce Category Flat Bootstarp Responsive Website Template | Home :: w3layouts</title>
<link href="~/Content/css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary JavaScript plugins) -->
<script type='text/javascript' src="~/Scripts/js/jquery-1.11.1.min.js"></script>
<!-- Custom Theme files -->
<link href="~/Content/css/style.css" rel='stylesheet' type='text/css' />
<!-- Custom Theme files -->
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Gretong Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700,900' rel='stylesheet' type='text/css'>
<!-- start menu -->
<link href="~/Content/css/megamenu.css" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="~/Scripts/js/megamenu.js"></script>
<script>$(document).ready(function(){$(".megamenu").megamenu();});</script>
<script src="~/Scripts/js/menu_jquery.js"></script>
<script src="~/Scripts/js/simpleCart.min.js"> </script>
</head>
<body>
    @{
        List<BaiTapLon.Models.Entities.TungSanPham> listTungSanPham = ViewBag.listTungSanPham;
    }
    <!-- header_top -->
    @RenderPage("~/Views/Share/header_top.cshtml");
    <!-- header -->
    @RenderPage("~/Views/Share/header.cshtml");
    <div class="container">
        <div class="check">
            <div class="col-md-3 cart-total">
                <a class="continue" href="#">Continue to basket</a>
                <div class="price-details">
                    <h3>Price Details</h3>
                    <span>Total</span>
                    <span class="simpleCart_total total1">6200.00</span>
                    <span>Discount</span>
                    <span class="total1">---</span>
                    <span>Delivery Charges</span>
                    <span class="total1">150.00</span>
                    <div class="clearfix"></div>
                </div>
                <ul class="total_price">
                    <li class="last_price"> <h4>TOTAL</h4></li>
                    <li class="last_price"><span class="simpleCart_total">6350.00</span></li>
                    <div class="clearfix"> </div>
                </ul>


                <div class="clearfix"></div>
                <a class="order" href="#">Place Order</a>
                <div class="total-item">
                    <h3>OPTIONS</h3>
                    <h4>COUPONS</h4>
                    <a class="cpns" href="#">Apply Coupons</a>
                    <p><a href="#">Log In</a> to use accounts - linked coupons</p>
                </div>
            </div>
            <div class="col-md-9 cart-items">
                <h1 id="count">My Shopping Bag @listTungSanPham.Count()</h1>

                @for (int i = 0; i < listTungSanPham.Count(); i++)
                {
            <script>
                        $(document).ready(function (c) {
                            $('.close-@i').on('click', function (c) {
                                $('.cart-header-@i').fadeOut('slow', function (c) {
                                    $('.cart-header-@i').remove();
                                });
                                $.ajax({
                                    url: "https://localhost:44307/deletesanpham",
                                    data:
                                    {
                                    id:@i
                                    },
                                    success: function (data) {
                                        if (data == "Success")
                                            alert("Xóa Thành Công");
                                        else
                                            alert("Xóa Không Thành Công");
                                    }
                                    });
                            });
                        });
            </script>
                    <div class="cart-header-@i cart-header">
                        <div class="close-@i close1"> </div>
                        <div class="cart-sec simpleCart_shelfItem">
                            <div class="cart-item cyc">
                                <img src="@listTungSanPham[i].Image" class="img-responsive" alt="" />
                            </div>
                            <div class="cart-item-info">
                                <h3>@Html.ActionLink(listTungSanPham[i].Name, "details", "BaiTapLon", new { Name = listTungSanPham[i].Name }, null)<span>Model No: 3578</span></h3>
                                <ul class="qty">
                                    <li><p>ShoeFirm : @listTungSanPham[i].ShoeFirm</p></li>
                                    @*<li><p>Qty : 1</p></li>*@
                                </ul>

                                <div class="delivery">
                                    <p>Service Charges : Rs.@listTungSanPham[i].Price.00</p>
                                    <span>Delivered in 2-3 bussiness days</span>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <div class="clearfix"></div>

                        </div>
                    </div>
                }

                @*<script>
                    $(document).ready(function (c) {
                        $('.close1').on('click', function (c) {
                            $('.cart-header').fadeOut('slow', function (c) {
                                $('.cart-header').remove();
                            });
                        });
                    });
                </script>
                <div class="cart-header">
                    <div class="close1"> </div>
                    <div class="cart-sec simpleCart_shelfItem">
                        <div class="cart-item cyc">
                            <img src="~/Content/images/8.jpg" class="img-responsive" alt="" />
                        </div>
                        <div class="cart-item-info">
                            <h3><a href="#">Mountain Hopper(XS R034)</a><span>Model No: 3578</span></h3>
                            <ul class="qty">
                                <li><p>Size : 5</p></li>
                                <li><p>Qty : 1</p></li>
                            </ul>

                            <div class="delivery">
                                <p>Service Charges : Rs.100.00</p>
                                <span>Delivered in 2-3 bussiness days</span>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                        <div class="clearfix"></div>

                    </div>
                </div>
                <script>
                    $(document).ready(function (c) {
                        $('.close2').on('click', function (c) {
                            $('.cart-header2').fadeOut('slow', function (c) {
                                $('.cart-header2').remove();
                            });
                        });
                    });
                </script>
                <div class="cart-header2">
                    <div class="close2"> </div>
                    <div class="cart-sec simpleCart_shelfItem">
                        <div class="cart-item cyc">
                            <img src="~/Content/images/11.jpg" class="img-responsive" alt="" />
                        </div>
                        <div class="cart-item-info">
                            <h3><a href="#">Mountain Hopper(XS R034)</a><span>Model No: 3578</span></h3>
                            <ul class="qty">
                                <li><p>Size : 5</p></li>
                                <li><p>Qty : 1</p></li>
                            </ul>
                            <div class="delivery">
                                <p>Service Charges : Rs.100.00</p>
                                <span>Delivered in 2-3 bussiness days</span>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                        <div class="clearfix"></div>

                    </div>
                </div>*@
            </div>


            <div class="clearfix"> </div>
        </div>
    </div>
    @RenderPage("~/Views/Share/footer.cshtml");
</body>
</html>

BaiTapLon/Views/BaiTapLon/contact.cshtml
<!DOCTYPE HTML>
<html>
<head>
<title>Gretong a Ecommerce Category Flat Bootstarp Responsive Website Template | Contact :: w3layouts</title>
<link href="~/Content/css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary JavaScript plugins) -->
<script type='text/javascript' src="js/jquery-1.11.1.min.js"></script>
<!-- Custom Theme files -->
<link href="~/Content/css/style.css" rel='stylesheet' type='text/css' />
<!-- Custom Theme files -->
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Gretong Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700,900' rel='stylesheet' type='text/css'>
<!-- start menu -->
<link href="~/Content/css/megamenu.css" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="~/Scripts/js/megamenu.js"></script>
<script>$(document).ready(function(){$(".megamenu").megamenu();});</script>
<script src="~/Scripts/js/menu_jquery.js"></script>
</head>
<body>
    <!-- header_top -->
    @RenderPage("~/Views/Share/header_top.cshtml");
    <!-- header -->
    @RenderPage("~/Views/Share/header.cshtml");
    <!-- content -->
    <div class="container">
        <div class="main">
            <div class="contact">
                <div class="contact_info">
                    <h2>get in touch</h2>
                    <div class="map">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d424396.3176723366!2d150.92243255000002!3d-33.7969235!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6b129838f39a743f%3A0x3017d681632a850!2sSydney+NSW%2C+Australia!5e0!3m2!1sen!2sin!4v1430912648478" width="100%" height="250" frameborder="0" style="border:0"></iframe>
                    </div>
                </div>
                <div class="contact-form">
                    <h2>Contact Us</h2>
                    <form method="post" action="contact-post.html">
                        <div>
                            <span><label>Name</label></span>
                            <span><input name="userName" type="text" class="textbox"></span>
                        </div>
                        <div>
                            <span><label>E-mail</label></span>
                            <span><input name="userEmail" type="text" class="textbox"></span>
                        </div>
                        <div>
                            <span><label>Mobile</label></span>
                            <span><input name="userPhone" type="text" class="textbox"></span>
                        </div>
                        <div>
                            <span><label>Subject</label></span>
                            <span><textarea name="userMsg"> </textarea></span>
                        </div>
                        <div>
                            <span><input type="submit" class="" value="Submit us"></span>
                        </div>
                    </form>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    @RenderPage("~/Views/Share/footer.cshtml");
</body>
</html>

BaiTapLon/Views/BaiTapLon/index.cshtml
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Layout/_LayoutIndex.cshtml";

    List<BaiTapLon.Models.Entities.SanPham> sanPham = ViewBag.SanPham;
    Random random = new Random();
}
<div class="arriv">
    <div class="container">
        <div class="arriv-top">
            <div class="col-md-6 arriv-left">
                <img src="~/Content/images/1.jpg" class="img-responsive" alt="">
                <div class="arriv-info">
                    <h3>NEW ARRIVALS</h3>
                    <p>REVIVE YOUR WARDROBE WITH CHIC KNITS</p>
                    <div class="crt-btn">
                        <a href="details">TAKE A LOOK</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 arriv-right">
                <img src="~/Content/images/2.jpg" class="img-responsive" alt="">
                <div class="arriv-info">
                    <h3>TUXEDO</h3>
                    <p>REVIVE YOUR WARDROBE WITH CHIC KNITS</p>
                    <div class="crt-btn">
                        <a href="details">SHOP NOW</a>
                    </div>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<div class="special">
    <div class="container">
        <h3>Special Offers</h3>
        <div class="specia-top">
            <ul class="grid_2">
                @for (int i = 0; i < 4; i++)
                {
                    int j = random.Next(0, sanPham.Count());
                    <li>
                        <a href="https://localhost:44307/details?Name=@sanPham[j].Name"><img src="@sanPham[j].Image" class="img-responsive" alt=""></a>
                        <div class="special-info grid_1 simpleCart_shelfItem">
                            <h5>@sanPham[j].Name</h5>
                            <div class="item_add"><span class="item_price"><h6>ONLY $@sanPham[j].Price.00</h6></span></div>
                            <div class="item_add"><span class="item_price"><button id="@j">add to cart</button></span></div>
                        </div>
                    </li>
                    <script>
                    $(document).ready(function () {
                        $("#@j").click(function(){
                            $.ajax({
                                    url: "https://localhost:44307/addsanpham",
                                    data:
                                    {
                                    Image:"@sanPham[j].Image",
                                    Price:@sanPham[j].Price,
                                    Name: "@sanPham[j].Name",
                                    ShoeFirm:"@sanPham[j].ShoeFirm"
                                    },
                                    success: function (data) {
                                        if (data == "Success")
                                            alert("Thêm Thành Công");
                                        else
                                            alert("Thêm Không Thành Công");
                                    }
                                    });
                        });
                    });
                    </script>
                }
                <div class="clearfix"> </div>
            </ul>
        </div>
    </div>
</div>

BaiTapLon/Views/BaiTapLon/register.cshtml
 <!DOCTYPE HTML>
<html>
<head>
    <title>Gretong a Ecommerce Category Flat Bootstarp Responsive Website Template | Register :: w3layouts</title>
    <link href="~/Content/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <!-- jQuery (necessary JavaScript plugins) -->
    <script type='text/javascript' src="~/Scripts/js/jquery-1.11.1.min.js"></script>
    <!-- Custom Theme files -->
    <link href="~/Content/css/style.css" rel='stylesheet' type='text/css' />
    <!-- Custom Theme files -->
    <!--//theme-style-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Gretong Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700,900' rel='stylesheet' type='text/css'>
    <!-- start menu -->
    <link href="~/Content/css/megamenu.css" rel="stylesheet" type="text/css" media="all" />
    <script type="text/javascript" src="~/Scripts/js/megamenu.js"></script>
    <script>$(document).ready(function () { $(".megamenu").megamenu(); });</script>
    <script src="~/Scripts/js/menu_jquery.js"></script>
    <script src="~/Scripts/js/simpleCart.min.js"></script>
</head>
<body>
    <!-- header_top -->
    @RenderPage("~/Views/Share/header_top.cshtml");
    <!-- header -->
    @RenderPage("~/Views/Share/header.cshtml");
    <!-- content -->
    <div class="container">
        <div class="main">
            <!-- start registration -->
            <div class="registration">
                <div class="registration_left">
                    <h2>new user? <span> create an account </span></h2>
                    <div class="registration_form">
                        <!-- Form -->
                        <form id="registration_form">
                            <div>
                                <label>
                                    <input placeholder="first name:" type="text" id="firstName">
                                </label>
                            </div>
                            <div>
                                <label>
                                    <input placeholder="last name:" type="text" id="lastName">
                                </label>
                            </div>
                            <div>
                                <label>
                                    <input placeholder="email address:" type="email" id="email11">
                                </label>
                            </div>
                            <div class="sky-form">
                                <div class="sky_form1">
                                    <ul>
                                        <li><label class="radio left"><input type="radio" name="radio" checked=""><i></i>Male</label></li>
                                        <li><label class="radio"><input type="radio" name="radio"><i></i>Female</label></li>
                                        <div class="clearfix"></div>
                                    </ul>
                                </div>
                            </div>
                            <div>
                                <label>
                                    <input id="password11" placeholder="password" type="text" >
                                </label>
                            </div>
                            <div>
                                <label>
                                    <input placeholder="retype password" type="password" tabindex="4" required>
                                </label>
                            </div>
                            <div>
                                <input type="button" value="create an account" id="register-submit">
                            </div>
                            <div class="sky-form">
                                <label class="checkbox"><input type="checkbox" name="checkbox"><i></i>i agree to shoppe.com &nbsp;<a class="terms" href="#"> terms of service</a> </label>
                            </div>

                            <script>
                                $(document).ready(function () {
                                    $("#register-submit").click(function () {
                                        $.ajax({
                                            url: "/creatuser",
                                            type: "POST",
                                            data: { FirstName: $("#firstName").val(), LastName: $("#lastName").val(), Email: $("#email11").val(), Sex: true, Password: $("#password11").val() },
                                            success: function (data) {
                                                alert(data);
                                                if (data == "Success")
                                                    alert("Thêm Thành Công");
                                                else
                                                    alert("Thêm Không Thành Công");
                                            }
                                        });
                                    });
                                });
                            </script>
                        </form>
                        <!-- /Form -->
                    </div>
                </div>
                <div class="registration_left">
                    <h2>existing user</h2>
                    <div class="registration_form">
                        <!-- Form -->
                        <form id="registration_form" action="contact.php" method="post">
                            <div>
                                <label>
                                    <input placeholder="email:" type="email" tabindex="3" required>
                                </label>
                            </div>
                            <div>
                                <label>
                                    <input placeholder="password" type="password" tabindex="4" required>
                                </label>
                            </div>
                            <div>
                                <input type="submit" value="sign in" id="register-submit">
                            </div>
                            <div class="forget">
                                <a href="#">forgot your password</a>
                            </div>
                        </form>
                        <!-- /Form -->
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <!-- end registration -->
        </div>
    </div>
    @RenderPage("~/Views/Share/footer.cshtml");
</body>
</html>